[[library]]
type="pkgconfig"
name="fdk-aac"
includes=["fdk-aac/aacdecoder_lib.h"]

[[library]]
type="pkgconfig"
name="ffmpeg"
includes=["libavcodec/avcodec.h", "libavutil/avutil.h", "libavutil/imgutils.h", "libavutil/pixdesc.h", "libswscale/swscale.h"]

[[library]]
type="pkgconfig"
name="libplist"
includes=["plist/plist.h"]

[[library]]
type="file"
name="llhttp"
path="UxPlay/lib/llhttp"
includes=["llhttp/llhttp.h"]

[[library]]
type="pkgconfig"
name="openssl"
includes=["openssl/evp.h", "openssl/sha.h"]

[[library]]
type="file"
name="playfair"
path="UxPlay/lib/playfair"
includes=["playfair/playfair.h"]
[[library]]

type="file"
name="uxplay"
path="UxPlay/lib"
includes=["raop.h"]
incdir="../lib"
