name: New obs-airplay Release
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install requirements
        uses: gerlero/apt-install@v1
        with:
          packages: clang pkg-config libssl-dev libswscale-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev git libobs-dev libavahi-compat-libdnssd-dev libplist-dev libfdk-aac-dev
          cache: false
      - name: Checkout Coddle repository
        uses: actions/checkout@v4
        with:
          repository: coddle-cpp/coddle
      - name: build and install coddle
        run: ./build.sh && sudo ./deploy.sh
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build obs-airplay plugin
        run: coddle
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-airplay_${{ runner.os }}-${{ runner.arch }}
          path: obs-airplay.so
