name: New obs-airplay Release
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: install apt requirements
        uses: gerlero/apt-install@v1
        with:
          packages: clang pkg-config libssl-dev libswscale-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev git libobs-dev libavahi-compat-libdnssd-dev libplist-dev libfdk-aac-dev
          cache: false
      - name: install coddle
        run: |
          git clone https://github.com/coddle-cpp/coddle.git && cd coddle && ./build.sh
          sudo ./deploy.sh
          cd ..
      - name: build
        run: coddle
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86_64
          path: obs-airplay.so
